sudo: required
dist: trusty
language: node_js
node_js: [12, 13]
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - yarn global add codecov
  - yarn
script:
  - yarn test
  - codecov
