name: Build Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Environment log
        id: env
        run: |
          node --version
          yarn --version

      - name: Install dependecies
        run: |
          yarn

      - name: Run build process
        run: |
          yarn build

      - name: Run testing
        run: |
          yarn test
          yarn test:build
        env:
          COVERAGE: 1

      - name: Upload test coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
